<?php
/**
 * You may not change or alter any portion of this comment or credits
 * of supporting developers from this source code or any supporting source code
 * which is considered copyrighted (c) material of the original comment or credit authors.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
 */

/**
 * SmallWorld
 *
 * @copyright    The XOOPS Project (https://xoops.org)
 * @copyright    2011 Culex
 * @license      GNU GPL (http://www.gnu.org/licenses/gpl-2.0.html/)
 * @package      SmallWorld
 * @since        1.0
 * @author       Michael Albertsen (http://culex.dk) <culex@culex.dk>
 */

// Array for gender
$arr0 = [_SMALLWORLD_CHOOSE, _SMALLWORLD_WOMAN, _SMALLWORLD_MAN];

// Array for "interested in gender(s)"
$arr01 = [_SMALLWORLD_WOMAN, _SMALLWORLD_MAN, _SMALLWORLD_BOTH, _SMALLWORLD_NONE];

// Array for marital status
$arr02 = [_SMALLWORLD_MARRIED, _SMALLWORLD_ENGAGED, _SMALLWORLD_SINGLE, _SMALLWORLD_RELATIONSHIP, _SMALLWORLD_RELATIONSHIP_OPEN, _SMALLWORLD_ITSCOMP];

// Array for searchin for
$arr03 = [_SMALLWORLD_FRIENDSHIP, _SMALLWORLD_DATING, _SMALLWORLD_ARELATIONSHIP, _SMALLWORLD_HANKYPANKY];

// array politics
$arr04 = [_SMALLWORLD_PVLIBERAL, _SMALLWORLD_PLIBERAL, _SMALLWORLD_PMODERATE, _SMALLWORLD_PCONSERVATIVE, _SMALLWORLD_PVCONSERVATIVE, _SMALLWORLD_PLIBERTARIAN, _SMALLWORLD_POTHER];

// Array religions
$arr05 = [
    _SMALLWORLD_RCHRISTIANITY,
    _SMALLWORLD_RISLAM,
    _SMALLWORLD_RSECULAR,
    _SMALLWORLD_RHINDUISM,
    _SMALLWORLD_RCHINESETRAD,
    _SMALLWORLD_RBUDDHISM,
    _SMALLWORLD_RPRIMALIND,
    _SMALLWORLD_RAFRICANTRAD,
    _SMALLWORLD_RSIKHISM,
    _SMALLWORLD_RJUCHE,
    _SMALLWORLD_RSPIRITISM,
    _SMALLWORLD_RJUDAISM,
    _SMALLWORLD_RBAHAI,
    _SMALLWORLD_RJAINISM,
    _SMALLWORLD_RSHINTO,
    _SMALLWORLD_RCAODAI,
    _SMALLWORLD_RZOROASRIANISM,
    _SMALLWORLD_RTENRIKYO,
    _SMALLWORLD_RNEOPAGANISM,
    _SMALLWORLD_RUNITARIANUNIVERSALISM,
    _SMALLWORLD_RRASTA,
    _SMALLWORLD_RSCIENTOLOGY,
    _SMALLWORLD_ANCIENTALIENTHEORIST,
    _SMALLWORLD_ROTHER
];

// Array Screen names
$arr06 = [
    _SMALLWORLD_SCREENNAME_AIM,
    _SMALLWORLD_SCREENNAME_FACEBOOK,
    _SMALLWORLD_SCREENNAME_GOOGLE,
    _SMALLWORLD_SCREENNAME_ICQ,
    _SMALLWORLD_SCREENNAME_SKYPE,
    _SMALLWORLD_SCREENNAME_TWITTER,
    _SMALLWORLD_SCREENNAME_MYSPACE,
    _SMALLWORLD_SCREENNAME_XOOPS,
    _SMALLWORLD_SCREENNAME_YAHOO,
    _SMALLWORLD_SCREENNAME_YOUTUBE
];

$arr7 = [
    _SMALLWORLD_KINDERGARDEN,
    _SMALLWORLD_NURSERY,
    _SMALLWORLD_ELEMSCHOOL,
    _SMALLWORLD_GRADUATESCHOOL,
    _SMALLWORLD_HIGHSCHOOL,
    _SMALLWORLD_JUNIORHIGH,
    _SMALLWORLD_JUNIORCOLLEGE,
    _SMALLWORLD_COLLEGE,
    _SMALLWORLD_TECNICAL,
    _SMALLWORLD_UNIVERSITY
];
